# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('tags', models.ManyToManyField(to='tags.Tag')),
            ],
        ),
    ]
